import { MenuItem } from './types.ts';

export const IMG_BASE = "https://raw.githubusercontent.com/stejlovv-afk/menu/main/";

export const CATEGORIES: { id: string; label: string }[] = [
  { id: 'coffee', label: 'Кофе' },
  { id: 'tea', label: 'Чай' },
  { id: 'punsh', label: 'Пунши' },
  { id: 'seasonal', label: 'Сезонные' },
  { id: 'ice', label: 'Холодные' },
  { id: 'food', label: 'Сладости' },
  { id: 'drinks', label: 'Газировка' },
];

export const MILKS = ["Обычное", "Кокосовое", "Банановое", "Миндальное", "Безлактозное"];
export const SYRUPS = ["Фисташка", "Лесной орех", "Кокос", "Миндаль", "Лаванда", "Малина", "Соленая карамель"];

export const MENU_ITEMS: MenuItem[] = [
    { id: 1, cat: 'coffee', name: "Капучино", sizes: {"250":190, "350":230, "450":270}, img: "kapuchino-min.jpg" },
    { id: 2, cat: 'coffee', name: "Латте", sizes: {"250":190, "350":230, "450":270}, img: "latte-min.jpg" },
    { id: 3, cat: 'coffee', name: "Эспрессо", sizes: {"30":110, "60":150}, img: "espresso1-min.jpg", noMilk: true },
    { id: 4, cat: 'coffee', name: "Американо", sizes: {"250":180, "350":220, "450":260}, img: "americano-min.jpg", noMilk: true },
    { id: 5, cat: 'coffee', name: "Флат Уайт", sizes: {"250":220, "350":260, "450":360}, img: "kapuchino-min.jpg" },
    { id: 6, cat: 'coffee', name: "Раф", sizes: {"250":210, "350":250, "450":290}, img: "latte-min.jpg" },
    { id: 7, cat: 'coffee', name: "Бамбл Теплый", sizes: {"250":270, "350":270, "450":300}, img: "kapuchino-min.jpg", isBumble: true },
    { id: 20, cat: 'tea', name: "Чай Черный", sizes: {"350":120, "450":180}, img: "teablack-min.jpg" },
    { id: 21, cat: 'tea', name: "Чай Зеленый", sizes: {"350":120, "450":180}, img: "greentea-min.jpg" },
    { id: 22, cat: 'tea', name: "Чай Каркаде", sizes: {"350":120, "450":180}, img: "karkadetea-min.jpg" },
    { id: 23, cat: 'tea', name: "Чай Зеленый Жасмин", sizes: {"350":120, "450":180}, img: "greenjasmin-min.jpg" },
    { id: 24, cat: 'tea', name: "Чай Травяной", sizes: {"350":120, "450":180}, img: "travatea-min.jpg" },
    { id: 25, cat: 'tea', name: "Матча", sizes: {"250":180, "350":220, "450":260}, img: "matcha-min.jpg" },
    { id: 26, cat: 'tea', name: "Какао", sizes: {"250":180, "350":220, "450":260}, img: "kakao-min.jpg" },
    { id: 27, cat: 'tea', name: "Пряный чай", sizes: {"250":240, "350":280, "450":320}, img: "kakao-min.jpg" },
    { id: 28, cat: 'tea', name: "Горячий шоколад", price: 180, img: "kakao-min.jpg" },
    { id: 29, cat: 'tea', name: "Глинтвейн", sizes: {"350":230, "450":270}, img: "glintveinpunch-min.jpg" },
    { id: 50, cat: 'punsh', name: "Облепиховый пунш", sizes: {"350":230, "450":270}, img: "oblepihapunch-min.jpg" },
    { id: 51, cat: 'punsh', name: "Малиновый пунш", sizes: {"350":230, "450":270}, img: "malinapunsh-min.jpg" },
    { id: 80, cat: 'seasonal', name: "Латте Халва", sizes: {"350":290, "450":350}, img: "lattehalva-min.jpg", noSyrup: true },
    { id: 81, cat: 'seasonal', name: "Латте Тыква", sizes: {"350":290, "450":350}, img: "lattetikva-min.jpg", noSyrup: true },
    { id: 82, cat: 'seasonal', name: "Раф Сникерс", sizes: {"350":320, "450":380}, img: "rafsnikers-min.jpg", noSyrup: true },
    { id: 83, cat: 'seasonal', name: "Латте Orange Christmas", sizes: {"350":320, "450":380}, img: "latteorangecristmas-min.jpg", noSyrup: true },
    { id: 60, cat: 'ice', name: "Айс Латте", sizes: {"250":240, "350":280}, img: "latte-min.jpg" },
    { id: 61, cat: 'ice', name: "Эспрессо Тоник", sizes: {"250":250, "350":290}, img: "granattonic-min.jpg" },
    { id: 62, cat: 'ice', name: "Бамбл Холодный", sizes: {"270":270, "300":300}, img: "kapuchino-min.jpg", isBumble: true },
    { id: 63, cat: 'ice', name: "Айс Матча", sizes: {"230":230, "270":270}, img: "matcha-min.jpg" },
    { id: 64, cat: 'ice', name: "Лимонад (Киви/Манго/Смор)", sizes: {"260":260, "290":290}, img: "lemonchernogo-min.jpg" },
    { id: 100, cat: 'food', name: "Bombbar Лесной орех", price: 130, img: "bombbarfunduk-min.jpg" },
    { id: 101, cat: 'food', name: "Bombbar Малиновый", price: 130, img: "bombbarfunduk-min.jpg" },
    { id: 102, cat: 'food', name: "Bombbar Кокос", price: 130, img: "bombbarfunduk-min.jpg" },
    { id: 103, cat: 'food', name: "Snaqer Орех/Карамель", price: 130, img: "snaqerfunduk-min.jpg" },
    { id: 104, cat: 'food', name: "Печенье Chika Смородина", price: 170, img: "chikabiscuitbanan-min.jpg" },
    { id: 105, cat: 'food', name: "Печенье Chika Банан", price: 170, img: "chikabiscuitbanan-min.jpg" },
    { id: 106, cat: 'food', name: "Жвачка Эклипс", price: 80, img: "eclipce.jpg" },
    { id: 107, cat: 'food', name: "Горький шоколад", price: 80, img: "chokolatgorkiy.jpg" },
    { id: 108, cat: 'food', name: "Молочный шоколад", price: 80, img: "chokolatgorkiy.jpg" },
    { id: 109, cat: 'food', name: "Choco Pie", price: 30, img: "chudo.jpg" },
    { id: 110, cat: 'food', name: "Батончик Чудо", price: 60, img: "chudo.jpg" },
    { id: 111, cat: 'food', name: "Бабаевский батончик", price: 100, img: "babka.jpg" },
    { id: 200, cat: 'drinks', name: "Черноголовка Cola", price: 140, img: "colachernogo-min.jpg" },
    { id: 201, cat: 'drinks', name: "Черноголовка Байкал", price: 140, img: "colachernogo-min.jpg" },
    { id: 202, cat: 'drinks', name: "Черноголовка газ/негаз", price: 70, img: "negazcernogo-min.jpg" },
    { id: 203, cat: 'drinks', name: "Черноголовка лимонад", price: 140, img: "colachernogo-min.jpg" },
    { id: 204, cat: 'drinks', name: "Cosmos Тропический", price: 130, img: "cosmos.jpg" },
    { id: 205, cat: 'drinks', name: "Cosmos Оригинальный", price: 130, img: "cosmos.jpg" },
    { id: 206, cat: 'drinks', name: "Adrenaline Без сахара", price: 200, img: "adrenalin.jpg" },
    { id: 207, cat: 'drinks', name: "Adrenaline Оригинальный", price: 200, img: "adrenalin.jpg" },
    { id: 208, cat: 'drinks', name: "Сок Il Primo Томат", price: 120, img: "iltomato.jpg" },
    { id: 209, cat: 'drinks', name: "Сок Il Primo Яблоко", price: 120, img: "iltomato.jpg" },
    { id: 210, cat: 'drinks', name: "Сок Il Primo Апельсин", price: 120, img: "iltomato.jpg" },
    { id: 211, cat: 'drinks', name: "Lipton Персик", price: 130, img: "lipton.jpg" },
    { id: 212, cat: 'drinks', name: "Дикий апельсин-Юдзу", price: 110, img: "chernogolovkaorange.jpg" }
];
